pipeline {
    agent any

    environment {
        IMAGE_NAME = "react-cicd-app"
        CONTAINER_NAME = "react-prod"
        DEPLOY_BRANCH = "main"
    }

    stages {

        stage('Checkout Code') {
            when {
                branch DEPLOY_BRANCH
            }
            steps {
                git branch: 'main',
                    url: 'https://github.com/ganesha2208/AWS_FirstReact.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build React App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Deploy to Production') {
            steps {
                sh '''
                docker rm -f $CONTAINER_NAME || true
                docker run -d -p 3000:3000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo "✅ React App Deployed Successfully"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}

